### Profile registration
POST localhost:8080/profile/registration
Content-Type: application/json

{
  "name": "Ali",
  "surname": "Aliyev",
  "phone": "998915721213",
  "password": "123456",
  "role": "ROLE_ADMIN"
}